version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: louvor4_postgres_db
    environment:
      POSTGRES_USER: louvor4
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: louvor4db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
